Chapter2/mysite/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # blog list views
    url(r'^$',
        views.post_list,
        name='post_list'),
    # blog list by tag
    url(r'^tag/(?P<tag_slug>[-\w]+)$',
        views.post_list,
        name='post_list_by_tag'),
    # url(r'^$',
    #     views.PostListView.as_view(),
    #     name='post_list'),
    # blog detail views with tags
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    #
    url(r'^(?P<post_id>\d+)/share/$',
        views.post_share,
        name='post_share'),
]

Chapter2/mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',
                           namespace='blog',
                           app_name='blog')),
]

Chapter2/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    # title of blog, transfer to VARCHAR in SQL
    title = models.CharField(max_length=250)
    # a short tag, use in the URLs
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    # a ForeignKey many-to-one, a blog can only be edited by one author, but one author can edit many blog.
    author = models.ForeignKey(User,
                               related_name='blog_posts')
    # body of blog, transfer to TEXT in SQL
    body = models.TextField()
    # This is just a timezone-aware datetime.now
    publish = models.DateTimeField(default=timezone.now)
    # save the time when the blog is created
    created = models.DateTimeField(auto_now_add=True)
    # save the time when the blog is updated
    updated = models.DateTimeField(auto_now=True)
    # https://docs.djangoproject.com/en/1.11/ref/models/fields/#choices
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    # add tag to the post
    tag = TaggableManager()

    # The default manager.
    objects = models.Manager()
    # Our custom manager.
    published = PublishedManager()

    # return the data by descent ordering
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # strftime : use to make sure 01, 02, 03 in month and day
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    # which post is the comment belong to
    post = models.ForeignKey(Post,
                             related_name='comments')
    # who comment this post
    name = models.CharField(max_length=80)
    #
    email = models.EmailField()
    # comment content
    body = models.TextField()
    # save the time when the blog is created
    created = models.DateTimeField(auto_now_add=True)
    # save the time when the blog is updated
    updated = models.DateTimeField(auto_now=True)
    # ban the inappropriate comments
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

Chapter2/mysite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        # create form according to Comment model
        model = Comment
        #
        fields = ('name', 'email', 'body')

Chapter2/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm


# Create your views here.


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/list.html'


def post_list(request, tag_slug=None):
    # find all published blog
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        # get the tag object
        tag = get_object_or_404(Tag,
                                slug=tag_slug)
        # filter the specific tag
        object_list = object_list.filter(tag__in=[tag])
    # 3 posts in each page
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag':tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    # values_list return tuple, and flat=True return the list [1,2,3...]
    post_tag_ids = post.tag.values_list('id', flat=True)
    print(post_tag_ids)
    # exclude the current post
    similar_posts = Post.published.filter(tag__in=post_tag_ids).exclude(id=post.id)
    #
    similar_posts = similar_posts.annotate(same_tag=Count('tag')).order_by('-same_tag','-publish')[:4]

    return render(request,
                  'blog/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    # retrieve post by id
    post = get_object_or_404(Post,
                             id=post_id,
                             status='published')

    sent = False
    cd = None
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            print(cd)
            # ... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'],
                                                                   cd['email'],
                                                                   post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,
                                                                     post_url,
                                                                     cd['name'],
                                                                     cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,
                  'blog/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent,
                   'cd': cd})

Chapter2/mysite/blog/templates/blog/detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
{% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

Chapter2/mysite/blog/templates/blog/list.html
{% extends "base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
    <h2>Posts tagged with {{ tag.name }}</h2>
    {% endif %}
    {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">Tags:
        {% for tag in post.tag.all %}
         <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
             {{ tag.name }}
         </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    {% include 'pagination.html' with page=posts %}

    <!--for ListView-->
{#   {% include "pagination.html" with page=page_obj %} #}

{% endblock %}

Chapter2/mysite/blog/templates/blog/share.html
{% extends "base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ cd.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            <!--{{ form.as_p }}-->
            {% for field in form %}
            <div>
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
{% endfor %}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
         </form>
    {% endif %}
{% endblock %}